theme: jekyll-theme-cayman
title: Nest architecture and colony organization in ants
description: Data and scripts used to determine how nest shape affects the spatial organization of ants in the nest
